version: '3.9'

services:
  website:
    image: php:8.0-fpm
    volumes:
      - ./:/var/www
    working_dir: /var/www

  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80